### ISSUE TITLE
Team Project 5 - ZFR

### ISSUE THREAD

**Issue by shani-la** [einavshazo/Naot_learning#13]
Team Project 5 - ZFR : the late handing in is approved by Rueben.(We had to change our organization)

**Comment by ItamarShDev** [comment]
please add tags to the backlog issues, "client", "server", and such
project license should be presents in an inside box (using '> ' before each line)
also add the license to the readme

Iteration 1 - MVP link is broken

**Comment by ItamarShDev** [comment]
prototype should be clearer.
you have more than one page i guess, you need to reflect it in the prototype

**Comment by einavshazo** [comment]
Hi,we finished editing according to what we worked on during today's lesson.
We'd be happy to know if it's good so you can close the ZFR issue if it's O.K.

**Comment by ItamarShDev** [comment]
you still dont have a prototype in the ZFR page
